CREATE TABLE IF NOT EXISTS users
(
    id         bigint generated by default as identity not null,
    name       varchar(50),
    login      varchar(50)                             not null,
    password   varchar(255)                            not null,
    is_blocked boolean,
    email      varchar,
    constraint pk_user primary key (id),
    constraint uniq_login unique (login)
);

CREATE TABLE IF NOT EXISTS task
(
    id          bigint generated by default as identity not null,
    name        varchar(100),
    todolist_id bigint,
    description varchar(30000),
    file_id     bigint,
    constraint pk_task primary key (id)
);

CREATE TABLE IF NOT EXISTS todolist
(
    id       bigint generated by default as identity not null,
    owner_id bigint,
    name     varchar,
    constraint pk_todolist primary key (id)
);

CREATE TABLE IF NOT EXISTS todolist_task
(
    todolist_id bigint references todolist (id),
    task_id     bigint references task (id)
);

CREATE TABLE IF NOT EXISTS file
(
    id   bigint generated by default as identity not null,
    name varchar(255),
    type varchar,
    size bigint,
    file bytea,
    constraint pk_file primary key (id)
);

CREATE TABLE IF NOT EXISTS role
(
    id   bigint generated by default as identity not null,
    name varchar unique,
    constraint pk_role primary key (id)
);

CREATE TABLE IF not exists users_role
(
    user_id bigint references users (id),
    role_id bigint references role (id)
);

